/*
Copyright (c) 2025 Advanced Micro Devices, Inc. All rights reserved.

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
*/

syntax = "proto2";

package rocal_proto;

// Stores a single argument
message Arguments {
  required string name = 1;
  optional string type = 2;
  repeated float floats = 3;
  repeated int64 ints = 4;
  repeated string strings = 5;
  repeated bool bools = 6;

  // vector storage
  required bool is_vector = 8 [default = false];
}

// Stores info about each operator in pipeline
message OperatorDef {
  required string name = 1;
  optional string module_name = 2;
  // Arguments
  repeated Arguments args = 3;
}

// Stores pipeline arguments and a list of nodes/operators
message PipelineDef {
  optional int64 num_threads = 1 [default = 4];
  required int32 batch_size = 2;
  optional int32 device_id = 3 [default = 0];
  optional int64 seed = 4 [default = 1];
  optional bool rocal_cpu = 5 [default = true];
  optional int32 prefetch_queue_depth = 6 [default = 2];
  repeated OperatorDef operators = 7;
}